# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        s3.storage:
            adapter: 'aws'
            options:
                client: 's3_client' # The service ID of the Aws\S3\S3Client instance
                bucket: '%env(S3_BUCKET)%'
                # prefix: 'optional/path/prefix'
                # streamReads: true
